### PR TITLE
Bump Upjet to commit 2e361ad3b6e6

### PR DESCRIPTION
**Pull request by mergenci**
### Description of your changes

Bump Upjet to latest version: https://github.com/crossplane/upjet/commit/2e361ad3b6e6b225bbc560ecf7c92e88a7c3ae3a

Partially fixes https://github.com/crossplane-contrib/provider-upjet-aws/issues/1242.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

See Uptest runs linked:

1. [/test-examples="examples/autoscaling/v1beta1/autoscalinggroup.yaml"](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10510484773)
2. [/test-examples="examples/autoscaling/v1beta2/autoscalinggroup.yaml"](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10510490803)
3. [/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10510538491)
4. [/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10510549453)

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mergenci** [comment]
/test-examples="examples/autoscaling/v1beta1/autoscalinggroup.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/autoscaling/v1beta2/autoscalinggroup.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/ecs/v1beta2/taskdefinition.yaml"

**Review by turkenf — APPROVED** [review]
Thank you for this PR @mergenci. Also many thanks for handling the panics in async external clients 🙌

**Pull request merged**
