### PR TITLE
Bump Upjet to commit be5e036

### PR DESCRIPTION
**Pull request by mergenci**
### Description of your changes

I would like to consume Upjet PRs that come before https://github.com/crossplane/upjet/pull/424, so that changes because of those don't crowd https://github.com/crossplane-contrib/provider-upjet-aws/pull/1422. This PR consumes the following (listed in chronological order of merging):

1. https://github.com/crossplane/upjet/pull/441 (5cdf369)
2. https://github.com/crossplane/upjet/pull/413 (7eaaf8a)
3. https://github.com/crossplane/upjet/pull/289 (a18bd41)
4. https://github.com/crossplane/upjet/pull/449 (be5e036)

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

Uptest runs:

1. [examples/dynamodb/v1beta1/table.yaml](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12280167279)
2. [examples/ec2/v1beta2/vpcendpoint.yaml](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12280173419)
3. [examples/s3/v1beta1/bucket.yaml](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12280181305)
4. [examples/apigateway/v1beta2/restapi.yaml](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12280188277)
5. [examples/ssm/v1beta2/association.yaml](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12280195740)

Manual tests:

1. examples/ssm/v1beta1/maintenancewindowtask.yaml

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mergenci** [comment]
/test-examples="examples/ec2/v1beta1/vpcendpoint.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/s3/v1beta1/bucket.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/dynamodb/v1beta1/table.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by turkenf** [comment]
Thank you for the PR @mergenci, we need to backport the API changes in v1beta2 to v1beta1 here too :) It would also be good if we could test some of the resources we backported with uptest.

**Comment by mergenci** [comment]
Thanks for the catch @turkenf 💪 I committed each step of the backporting separately. I noticed that our automatic tooling is not able to handle new fields in renamed types. See https://github.com/crossplane-contrib/provider-upjet-aws/pull/1573/commits/318fcbb72cd1f28f513eccac213f8b7aaa92e055. I'll take a note of the situation in the documentation. I'll run Uptests as you suggested.

**Comment by mergenci** [comment]
/test-examples="examples/ssm/v1beta2/maintenancewindowtask.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/apigateway/v1beta2/restapi.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/ssm/v1beta2/association.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/dynamodb/v1beta1/table.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/s3/v1beta1/bucket.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/apigateway/v1beta2/restapi.yaml"

**Pull request merged**
