### PR TITLE
Add Bedrock Agent Support

### PR DESCRIPTION
**Pull request by blakeromano**
### Description of your changes

Adds Bedrock Agent

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

`make reviewable` passes.

I can run `make e2e UPTEST_EXAMPLE_LIST=examples/bedrockagent/v1beta1/agent.yaml` which does successfully create the resource. I believe https://github.com/hashicorp/terraform-provider-aws/issues/37168 is causing updates to fail which is solved in TF Provider version v5.64.0 which I think will ultimately block this from what I can tell.
Screenshot 2024-09-28 at 7 36 30 PM

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/bedrockagent/v1beta1/agent.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/bedrockagent/v1beta1/agent.yaml"

**Review by turkenf — APPROVED** [review]
Many thanks for your efforts on this PR @blakeromano. 

I had to rebase your PR and run make generate to be able to include it to today's release.

**Comment by blakeromano** [comment]
Appreciate it @turkenf!

**Pull request merged**
