### PR TITLE
Skip late initialization for several duplicate resource policy fields

### LINKED ISSUE #1207: [Bug]: IAM Role inlinePolicy conflicting with IAM RolePolicy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* iam.aws.upbound.io/v1beta1 - Role
* iam.aws.upbound.io/v1beta1 - RolePolicy

### Resource MRs required to reproduce the bug

```yaml
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: crossplane-test-role
spec:
  forProvider:
    assumeRolePolicy: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
              "AWS": "*"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
  providerConfigRef:
    name: default
```

```yaml
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicy
metadata:
  name: crossplane-test-policy
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "ec2:DescribeInstances",
            "Resource": [
              "*"
            ]
          }
        ]
      }
    role: crossplane-test-role
  providerConfigRef:
    name: default
```

### Steps to Reproduce

1. Create the Role and RolePolicy
2. Wait for the Role to be reconciled. Note the `inlinePolicy` field is now present on the role:
```yaml
inlinePolicy:
    - name: crossplane-test-policy
      policy: '{"Version":"2012-10-17","Statement":[{"Action":"ec2:DescribeInstances","Effect":"Allow","Resource":["*"]}]}'
```
3. Delete the RolePolicy
4. Note that the inline role policy has been removed
5. Wait until next reconciliation of the Role
6. Note that the inline role policy has been recreated due to the `inlinePolicy`

### What happened?

As no `inlinePolicy` was defined on the Role [it should not be managing inline policies](https://marketplace.upbound.io/providers/upbound/provider-aws-iam/v1.1.1/resources/iam.aws.upbound.io/Role/v1beta1#doc:spec-forProvider-inlinePolicy):
> If no blocks are configured, Crossplane will not manage any inline policies in this resource.

Setting `inlinePolicy: []` or `inlinePolicy: ~` has no effect and the field is removed during reconciliation.

### Relevant Error Output Snippet

_No response_

### Crossplane Version

1.15.0

### Provider Version

0.47.2

### Kubernetes Version

1.26

### Kubernetes Distribution

EKS 1.26

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by mbbush**
### Description of your changes

In several places in the terraform aws provider, there are two ways to specify a resource policy: a field named "policy" on the "foo" resource, and a separate resource named "foo_policy". 

If we'd realized this before we'd committed to a stable API, perhaps the best option would have been to only provide one of those options, but it's too late for that now.

This PR removes conflicts between the resource policy managed on the parent resource, and the resource policy managed on the Policy resource, by skipping Late Initialization of the `policy` field on the parent resource, for the following resources:

* Queue.sqs
* Topic.sns
* Role.iam (inlinePolicies)
* ~Key.kms~
* ~VpcEndpoint.ec2~
 
I made a semi-manual pass through the terraform aws provider docs, and these were the only examples I found, although I was not systematic and may have missed something. It seems like the resources with this behavior are the older resources, added to the terraform aws provider before they adopted more uniform best practices. 

I initially included the VPC endpoint and KMS key, which both have a `spec.forProvider.policy` field, and a separate resource in terraform provider aws that sets that policy. However, neither the `aws_kms_key_policy` nor `aws_vpc_endpoint_policy` resources exist in this provider yet. I'm undecided about whether it's better to skip late init for these parameters because we may someday implement the corresponding policy resource, whether we should avoid implementing those resources because the field already exists on the parent resource, or whether we should leave them be and defer the decision to the future. For now I've backed those commits out, but left them in the git history so they can be easily restored if desireable.

While I was going through I updated the config files to the latest standards as well.

Fixes #1207 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Running uptest on this PR.

I verified by looking at the uptest logs that the policy parameter was set in the status.atProvider and unset in the spec.forProvider, when that was expected, for:
- [x] Topic.sns (default policy)
- [x] Topic.sns (custom policy from a TopicPolicy resource)
- [x] Queue.sqs (custom policy from a QueuePolicy resource) 
- [x] Role.iam (custom policy from a RolePolicy resource)
- [x] Key.kms (on the commit that included it)
- [x] Key.kms (now that it's excluded, I verified that the policy *is* being late initialized.)

SQS queues have a default policy of `""`, and IAM roles have a default `inlinePolicies` that is null/empty array, so there's nothing to verify in the default case for those resources.

### CODE REVIEW

**Comment by mbbush** [comment]
/test-examples="examples/sns/v1beta1/topic.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/sns/v1beta1/topic.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/iam/v1beta1/role.yaml,examples/iam/v1beta1/role-with-inline-policy.yaml,examples/iam/v1beta1/rolepolicy.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/sqs/v1beta1/queue.yaml,examples/sqs/v1beta1/queuepolicy.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/kms/v1beta1/key.yaml"

**Comment by mbbush** [comment]
kms KeyPolicy doesn't seem to have an example manifest, and ec2 VpcEndpoint has one that clearly won't work. I'll try updating them when I get a chance.

**Comment by mbbush** [comment]
/test-examples="examples/kms/v1beta1/key.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/iam/v1beta1/user.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/iam/v1beta1/role.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/iam/v1beta1/usergroupmembership.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sns/v1beta1/topicsubscription.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sqs/v1beta1/queue.yaml"

**Comment by turkenf** [comment]
Not blocker: If possible and if not take much time, could you please make uptesable the [InstanceProfile.iam.aws.upbound.io/v1beta1](https://github.com/crossplane-contrib/provider-upjet-aws/blob/main/examples/iam/v1beta1/instanceprofile.yaml) resource with this PR?

**Comment by turkenf** [comment]
/test-examples="examples/iam/v1beta1/instanceprofile.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/s3/v1beta1/bucketnotification.yaml"

**Review by turkenf — APPROVED** [review]
Thank you for your effort in this PR @mbbush 🙌

**Pull request merged**
