### PR TITLE
feat(bump): 5.42.0

### PR DESCRIPTION
**Pull request by haarchri**
### Description of your changes
bump native tf-provider to v5.40.0

https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/8433252511/job/23093950721?pr=1240
```
Checking package/crds/cloud9.aws.upbound.io_environmentec2s.yaml for breaking API changes...
Breaking change detected!
Version "v1beta1":
- Schema changed
  - Properties changed
    - Modified property: spec
      - Properties changed
        - Modified property: forProvider
          - Required changed
            - New required property: imageId
```

```
Checking package/crds/dms.aws.upbound.io_eventsubscriptions.yaml for breaking API changes...
Breaking change detected!
Version "v1beta1":
- Schema changed
  - Properties changed
    - Modified property: spec
      - Properties changed
        - Modified property: forProvider
          - Required changed
            - Deleted required property: sourceIds
```

```
Checking package/crds/fsx.aws.upbound.io_ontapfilesystems.yaml for breaking API changes...
Breaking change detected!
Version "v1beta1":
- Schema changed
  - Properties changed
    - Modified property: spec
      - Properties changed
        - Modified property: forProvider
          - Required changed
            - Deleted required property: throughputCapacity
```

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by vibe** [comment]
Any reason why we wouldn't bump to [v5.42.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.42.0)

**Comment by mbbush** [comment]
> resource/aws_eks_access_entry: Always send kubernetes_groups and user_name values on update when configured 
That fix in particular from the 5.42.0 release notes seems like it would be useful for implementing a new means of authenticating in EKS clusters, which many of our users would appreciate. See #1098

**Comment by haarchri** [comment]
@vibe no i was playing around to get an idea what we need to do for version bump
@mbbush thanks will take a look

**Comment by haarchri** [comment]
@turkenf that means first we need to rebase the forked tf provider - doing a release and then we can go forward here ?

**Comment by haarchri** [comment]
Will we switch https://github.com/upbound/terraform-provider-aws to crossplane-contrib as well ?

**Comment by mbbush** [comment]
If we can find a way to eliminate or programmatically resolve the conflicts, it would be awesome to have a GitHub action that automatically updates our TF provider fork when upstream has a new release. 

This should be done later, but just sharing the idea

**Comment by haarchri** [comment]
thats fine - nobody outside the maintainer team can trigger the action ;) basically the Same i did - but first we need to rebase the provider tf fork

**Comment by haarchri** [comment]
tested https://github.com/upbound/terraform-provider-aws/pull/201 with `v5.42.0 `

for aws vpc it looks good

```
kubectl get managed
NAME                                SYNCED   READY   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/sample-vpc   True     True    vpc-0c7e92d4c27a819e4   19s
```

think we need one rebase from your branch @mbbush

**Comment by mbbush** [comment]
@haarchri Sorry for the late response. 

https://github.com/upbound/terraform-provider-aws/commit/4708239d78bc224bb08fbc8dcdcd236d7e6f1226 is a merge commit, and all the changes in the PR it merged are already included in my branch.

I cherry-picked in https://github.com/upbound/terraform-provider-aws/commit/fa992a10276b304275af098703739af230044ad0

https://github.com/upbound/terraform-provider-aws/commit/f2f0fdd63866b583c3b722434ace9b46b95fbe29 is the merge commit for fa992a1, and doesn't need to be included.

**Comment by mbbush** [comment]
@haarchri In addition to cherry-picking in the one non-merge commit you mentioned, I rebased onto the latest release and pushed as https://github.com/mbbush/terraform-provider-aws/tree/upjet-v5.46.0.

**Comment by turkenf** [comment]
Closed in favor of https://github.com/crossplane-contrib/provider-upjet-aws/pull/1271

**Pull request closed without merging**
