### PR TITLE
[do not merge] revert aws go sdk pinning to see if I can simulate the breakage

### PR DESCRIPTION
**Pull request by mbbush**
### Description of your changes

It looks like the solution to the clusterauth issue of pinning the go sdk breaks upgrading the terraform provider. I'm using this PR to experiment with alternative solutions.

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mbbush** [comment]
/test-examples="examples/eks/v1beta1/clusterauth.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/eks/v1beta1/clusterauth.yaml,examples/ec2/v1beta1/instance.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/eks/v1beta1/clusterauth.yaml,examples/ec2/v1beta1/instance.yaml"

**Comment by mbbush** [comment]
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/8770461647/job/24067041363 using aws sdk v1.24.1 is failing on the clusterauth step as expected.

**Comment by mbbush** [comment]
Simply upgrading to the latest sdk with no other changes fails to build with 
> Error: ../../../go/pkg/mod/github.com/upbound/terraform-provider-aws@v0.0.0-20240328111213-f2f0fdd63866/internal/service/emrserverless/application.go:731:27: cannot use int64(v) (value of type int64) as *int64 value in assignment

This is probably a result of https://github.com/aws/aws-sdk-go-v2/pull/2458

**Comment by mbbush** [comment]
Upgrading to the latest tf provider version fails to compile with 

```
# github.com/upbound/provider-aws/internal/clients
internal/clients/aws.go:243:19: tfAwsConnsClient.Session undefined (type *conns.AWSClient has no field or method Session)
```

Maybe I didn't include https://github.com/upbound/terraform-provider-aws/pull/196 into my fork correctly? Or maybe the change is incompatible with something done in `main` on the terraform provider?

**Comment by mbbush** [comment]
https://github.com/hashicorp/terraform-provider-aws/commit/b87c156fa3ac1199937815266d6f839b509572f3 This is why there's the error on `Session`

**Comment by mbbush** [comment]
@mergenci Any ideas why https://github.com/crossplane-contrib/provider-upjet-aws/pull/1274/commits/af4029c8246fd4d15c1f5f8e97b233bcaa39883c doesn't compile? I'm puzzled because I see essentially the same signature for other getters like https://github.com/hashicorp/terraform-provider-aws/commit/b87c156fa3ac1199937815266d6f839b509572f3#diff-2bef3ec311c0fa59f07b6d4b0f38154f51e02a7c4387384e70d8874bd1628d65R57 which I can use without problems.

**Comment by mergenci** [comment]
@mbbush, After conducting some source-code archeology, I unearthed that https://github.com/crossplane-contrib/provider-upjet-aws/commit/af4029c8246fd4d15c1f5f8e97b233bcaa39883c doesn't compile, because `conns.AWSClient.Session()`, introduced in https://github.com/hashicorp/terraform-provider-aws/commit/b87c156fa3ac1199937815266d6f839b509572f3, was removed in the next commit, https://github.com/hashicorp/terraform-provider-aws/commit/363e6a4d459532a3c467cda0c73999bb2fd74091 (see [file history](https://github.com/hashicorp/terraform-provider-aws/commits/363e6a4d459532a3c467cda0c73999bb2fd74091/internal/conns/awsclient.go)). [Current version of `awsclient.go`](https://github.com/mbbush/terraform-provider-aws/blob/0ec53cbccd61ca613bb47d410974f1cc5f05105e/internal/conns/awsclient.go), commit ID of which (0ec53cbccd61) is [referenced from `go.mod`](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1274/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R347), doesn't have the getter.

It looks like it should be safe to introduce the getter to `awsclient_xp.go` and have everything working as expected, but I haven't tested.

**Pull request closed without merging**
