### PR TITLE
Update CROSSPLANE_VERSION to 1.16.0 in Makefile

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR updates `CROSSPLANE_VERSION` to `1.16.0` in Makefile.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

Will test with uptest

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta1/vpc.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/v1beta1/clusterroleassociation.yaml"

**Comment by turkenf** [comment]
I think we need to address the issue in uptest in order to move this PR forward. 
```
    logger.go:42: 09:52:18 | case/0-apply |     - lastTransitionTime: "2024-05-29T09:38:18Z"
    logger.go:42: 09:52:18 | case/0-apply |       message: 'connect failed: cannot initialize the Terraform plugin SDK async external
    logger.go:42: 09:52:18 | case/0-apply |         client: cannot get terraform setup: cannot get referenced ProviderConfig:
    logger.go:42: 09:52:18 | case/0-apply |         "default": Timeout: failed waiting for *v1beta1.ProviderConfig Informer to
    logger.go:42: 09:52:18 | case/0-apply |         sync'
```
`FYI`: @sergenyalcin @ulucinar

**Comment by mbbush** [comment]
That looks like the same error message I started getting in uptest right after the uxp release of 1.15.0. IIRC it's a kubernetes permissions issue, caused by something about the way we're locally building each provider in the family is failing the crossplane "are these providers in the same family" check. It doesn't happen with production builds, just local ones.

This was the case in crossplane 1.15, but not in 1.14, and was the reason we pinned the crossplane version in the first place. It sounds like the issue is still present in 1.16. It could be resolved either at the crossplane level of how it detects family providers, or in the provider build tools for how we build the providers in the family. Probably updating our build to be closer to what happens in production would be a better solution, I just haven't investigated how to do that.

**Comment by haarchri** [comment]
yes the clusterroles are without the "familiy/config-provider" rbac rights

the packages are build correctly - and also the label is propagated correctly to the packagerevisions 
```
  labels:
    pkg.crossplane.io/provider-family: provider-family-aws
```

```
kubectl get clusterrole crossplane:provider:provider-aws-ec2-provider-aws:aggregate-to-view   -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2024-06-12T19:52:31Z"
  labels:
    rbac.crossplane.io/aggregate-to-view: "true"
  name: crossplane:provider:provider-aws-ec2-provider-aws:aggregate-to-view
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ProviderRevision
    name: provider-aws-ec2-provider-aws
    uid: 459fb0df-8c55-4036-8c9e-56e9dc1bd392
  resourceVersion: "1177"
  uid: 0add2bbb-234d-44a5-8221-0fcb74a6cd3b
rules:
- apiGroups:
  - ec2.aws.upbound.io
  resources:
  - amicopies
  - amicopies/status
  - amilaunchpermissions
  - amilaunchpermissions/status
  - amis
  - amis/status
  - availabilityzonegroups
  - availabilityzonegroups/status
  - capacityreservations
  - capacityreservations/status
  - carriergateways
  - carriergateways/status
  - customergateways
  - customergateways/status
  - defaultnetworkacls
  - defaultnetworkacls/status
  - defaultroutetables
  - defaultroutetables/status
  - defaultsecuritygroups
  - defaultsecuritygroups/status
  - defaultsubnets
  - defaultsubnets/status
  - defaultvpcdhcpoptions
  - defaultvpcdhcpoptions/status
  - defaultvpcs
  - defaultvpcs/status
  - ebsdefaultkmskeys
  - ebsdefaultkmskeys/status
  - ebsencryptionbydefaults
  - ebsencryptionbydefaults/status
  - ebssnapshotcopies
  - ebssnapshotcopies/status
  - ebssnapshotimports
  - ebssnapshotimports/status
  - ebssnapshots
  - ebssnapshots/status
  - ebsvolumes
  - ebsvolumes/status
  - egressonlyinternetgateways
  - egressonlyinternetgateways/status
  - eipassociations
  - eipassociations/status
  - eips
  - eips/status
  - flowlogs
  - flowlogs/status
  - hosts
  - hosts/status
  - instances
  - instances/status
  - instancestates
  - instancestates/status
  - internetgateways
  - internetgateways/status
  - keypairs
  - keypairs/status
  - launchtemplates
  - launchtemplates/status
  - mainroutetableassociations
  - mainroutetableassociations/status
  - managedprefixlistentries
  - managedprefixlistentries/status
  - managedprefixlists
  - managedprefixlists/status
  - natgateways
  - natgateways/status
  - networkaclrules
  - networkaclrules/status
  - networkacls
  - networkacls/status
  - networkinsightsanalyses
  - networkinsightsanalyses/status
  - networkinsightspaths
  - networkinsightspaths/status
  - networkinterfaceattachments
  - networkinterfaceattachments/status
  - networkinterfaces
  - networkinterfaces/status
  - networkinterfacesgattachments
  - networkinterfacesgattachments/status
  - placementgroups
  - placementgroups/status
  - routes
  - routes/status
  - routetableassociations
  - routetableassociations/status
  - routetables
  - routetables/status
  - securitygroupegressrules
  - securitygroupegressrules/status
  - securitygroupingressrules
  - securitygroupingressrules/status
  - securitygrouprules
  - securitygrouprules/status
  - securitygroups
  - securitygroups/status
  - serialconsoleaccesses
  - serialconsoleaccesses/status
  - snapshotcreatevolumepermissions
  - snapshotcreatevolumepermissions/status
  - spotdatafeedsubscriptions
  - spotdatafeedsubscriptions/status
  - spotfleetrequests
  - spotfleetrequests/status
  - spotinstancerequests
  - spotinstancerequests/status
  - subnetcidrreservations
  - subnetcidrreservations/status
  - subnets
  - subnets/status
  - tags
  - tags/status
  - trafficmirrorfilterrules
  - trafficmirrorfilterrules/status
  - trafficmirrorfilters
  - trafficmirrorfilters/status
  - transitgatewayconnectpeers
  - transitgatewayconnectpeers/status
  - transitgatewayconnects
  - transitgatewayconnects/status
  - transitgatewaymulticastdomainassociations
  - transitgatewaymulticastdomainassociations/status
  - transitgatewaymulticastdomains
  - transitgatewaymulticastdomains/status
  - transitgatewaymulticastgroupmembers
  - transitgatewaymulticastgroupmembers/status
  - transitgatewaymulticastgroupsources
  - transitgatewaymulticastgroupsources/status
  - transitgatewaypeeringattachmentaccepters
  - transitgatewaypeeringattachmentaccepters/status
  - transitgatewaypeeringattachments
  - transitgatewaypeeringattachments/status
  - transitgatewaypolicytables
  - transitgatewaypolicytables/status
  - transitgatewayprefixlistreferences
  - transitgatewayprefixlistreferences/status
  - transitgatewayroutes
  - transitgatewayroutes/status
  - transitgatewayroutetableassociations
  - transitgatewayroutetableassociations/status
  - transitgatewayroutetablepropagations
  - transitgatewayroutetablepropagations/status
  - transitgatewayroutetables
  - transitgatewayroutetables/status
  - transitgateways
  - transitgateways/status
  - transitgatewayvpcattachmentaccepters
  - transitgatewayvpcattachmentaccepters/status
  - transitgatewayvpcattachments
  - transitgatewayvpcattachments/status
  - volumeattachments
  - volumeattachments/status
  - vpcdhcpoptionsassociations
  - vpcdhcpoptionsassociations/status
  - vpcdhcpoptions
  - vpcdhcpoptions/status
  - vpcendpointconnectionnotifications
  - vpcendpointconnectionnotifications/status
  - vpcendpointroutetableassociations
  - vpcendpointroutetableassociations/status
  - vpcendpoints
  - vpcendpoints/status
  - vpcendpointsecuritygroupassociations
  - vpcendpointsecuritygroupassociations/status
  - vpcendpointserviceallowedprincipals
  - vpcendpointserviceallowedprincipals/status
  - vpcendpointservices
  - vpcendpointservices/status
  - vpcendpointsubnetassociations
  - vpcendpointsubnetassociations/status
  - vpcipampoolcidrallocations
  - vpcipampoolcidrallocations/status
  - vpcipampoolcidrs
  - vpcipampoolcidrs/status
  - vpcipampools
  - vpcipampools/status
  - vpcipamscopes
  - vpcipamscopes/status
  - vpcipams
  - vpcipams/status
  - vpcipv4cidrblockassociations
  - vpcipv4cidrblockassociations/status
  - vpcpeeringconnectionaccepters
  - vpcpeeringconnectionaccepters/status
  - vpcpeeringconnectionoptions
  - vpcpeeringconnectionoptions/status
  - vpcpeeringconnections
  - vpcpeeringconnections/status
  - vpcs
  - vpcs/status
  - vpnconnectionroutes
  - vpnconnectionroutes/status
  - vpnconnections
  - vpnconnections/status
  - vpngatewayattachments
  - vpngatewayattachments/status
  - vpngatewayroutepropagations
  - vpngatewayroutepropagations/status
  - vpngateways
  - vpngateways/status
  verbs:
  - get
  - list
  - watch
```

**Pull request closed without merging**
