### PR TITLE
Add MlflowTrackingServer resource to Sagemaker

### PR DESCRIPTION
**Pull request by Ezzmo**
### Description of your changes

This PR adds the `mlflowtrackingservers.sagemaker.aws.upbound.io` resource

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Uptest run: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12409081413

I tested locally with uptest. The MlFlow tracking server created successfully and tasks succeeded

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
Could you please add a valid example manifest under the `examples/sagemaker/v1beta1/..`, thank you!

Screenshot 2024-12-17 at 16 44 47

**Comment by turkenf** [comment]
/test-examples="examples/sagemaker/v1beta1/mlflowtrackingserver.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sagemaker/v1beta1/mlflowtrackingserver.yaml"

**Comment by turkenf** [comment]
This is a continuation of PR: https://github.com/crossplane-contrib/provider-upjet-aws/pull/1564

**Review by turkenf — APPROVED** [review]
Thank you for all your efforts to addding this resource @Ezzmo 🙌

**Comment by kujon** [comment]
@turkenf do you have any estimate on when this is going to be released?

**Pull request merged**
