### PR TITLE
Bump Terraform provider version to v5.58.0

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR bumps the Terraform provider version to `v5.58.0`

Fixes https://github.com/crossplane-contrib/provider-upjet-aws/issues/1420

I have:

- [X] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

- `examples/autoscaling/v1beta1/autoscalinggroup.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10005133970
- `examples/autoscaling/v1beta2/autoscalinggroup.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10047437956
- `examples/autoscaling/v1beta3/autoscalinggroup.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10047820140
- `examples/cloudtrail/v1beta1/eventdatastore.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10047882519
- `examples/docdb/v1beta1/cluster.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10047916708
- `examples/dynamodb/v1beta2/table.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10005347844
- `examples/ec2/v1beta1/customergateway.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9996968574
- `examples/ec2/v1beta2/route.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10005180322
- `examples/ec2/v1beta2/vpcendpoint.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10048071461
- `examples/ecs/v1beta2/taskdefinition.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10048135047
- `examples/fsx/v1beta2/lustrefilesystem.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10048177396
- `examples/iot/v1beta2/topicrule.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10048308532
- `examples/kafkaconnect/v1beta2/customplugin.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10048360929
- `examples/kms/v1beta1/grant.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9996967784
- `examples/mq/v1alpha1/user.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9996507494
- `examples/rds/v1beta2/cluster.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10048734272
- `examples/sagemaker/v1beta2/domain.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10055298605
- `examples/sagemaker/v1beta2/userprofile.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10055833955
- `examples/sagemaker/v1beta2/workforce.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10055918804
- `examples/sagemaker/v1beta2/workteam.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10056269624
- `examples/ssm/v1beta2/association.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10055995322
- `examples/apigateway/v1beta1/deployment.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10080019395
- `examples/appstream/v1beta2/fleet.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10081065228
- `examples/cloudformation/v1beta2/stacksetinstance.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10081068103
- `examples/ec2/v1beta2/launchtemplate.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10081966939
- `examples/glue/v1beta2/catalogtable.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10082258259
- `examples/opensearch/v1beta1/domain.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10084237174
- `examples/opensearch/v1beta2/domain.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10084758631
- `examples/pipes/v1beta1/pipe.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10143393423
- `examples/appsync/v1beta1/apikey.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10143755376

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta1/vpc.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta1/customergateway.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/kms/v1beta1/grant.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/v1beta2/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/v1beta1/clusterauth.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/mq/v1alpha1/user.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/v1beta2/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/kms/v1beta1/grant.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta1/customergateway.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appsync/v1beta1/apikey.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/autoscaling/v1beta1/autoscalinggroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dynamodb/v1beta2/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/v1beta2/nodegroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/route.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dynamodb/v1beta2/table.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta1/stage.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appstream/v1beta2/fleet.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appsync/v1beta1/apikey.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/autoscaling/v1beta2/autoscalinggroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/autoscaling/v1beta3/autoscalinggroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudformation/v1beta2/stacksetinstance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudtrail/v1beta1/eventdatastore.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/docdb/v1beta1/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/launchtemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ecs/v1beta2/taskdefinition.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/fsx/v1beta2/lustrefilesystem.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/glue/v1beta2/catalogtable.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/iot/v1beta2/topicrule.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/kafkaconnect/v1beta2/customplugin.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/kinesisanalyticsv2/v1beta2/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/opensearch/v1beta2/domain.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/v1beta2/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sagemaker/v1beta2/domain.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sagemaker/v1beta2/userprofile.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sagemaker/v1beta2/workforce.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ssm/v1beta2/association.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sagemaker/v1beta2/workteam.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta1/deployment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta1/deployment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appstream/v1beta2/fleet.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appstream/v1beta2/fleet.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudformation/v1beta2/stacksetinstance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/launchtemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/glue/v1beta2/catalogtable.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/opensearch/v1beta2/domain.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/opensearch/v1beta2/domain.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/opensearch/v1beta1/domain.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/opensearch/v1beta2/domain.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/eks/v1beta2/cluster.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/eks/v1beta2/cluster.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/eks/v1beta2/cluster.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/eks/v1beta2/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/pipes/v1beta1/pipe.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/pipes/v1beta1/pipe.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appsync/v1beta1/apikey.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/launchtemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/v1beta1/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta1/vpcendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/sagemaker/v1beta1/domain.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/ssm/v1beta2/association.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/v1beta1/clusterauth.yaml"

**Review by mergenci — APPROVED** [review]
Thanks @turkenf. LGTM.

**Review by turkenf — COMMENTED** [review]
Thank you @mergenci, LGTM.

**Pull request merged**
