### PR TITLE
feat(opensearch): connection details for opensearch clusters

### PR DESCRIPTION
**Pull request by aiell0**
### Description of your changes

Implements https://github.com/crossplane-contrib/provider-upjet-aws/issues/1442

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

I ran a make uptest on my own AWS EKS cluster on the example that was modified as part of this PR, and the cluster address was properly printed.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/opensearch/v1beta1/domain.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/opensearch/v1beta2/domain.yaml"

**Review by turkenf — COMMENTED** [review]
Thank you @aiell0, could you squash your commits? It would help keep the commit history cleaner and more organized.

**Comment by aiell0** [comment]
@turkenf I messed up doing the squash and went too far back, just closed/reopened a PR with the same changes (sorry): https://github.com/crossplane-contrib/provider-upjet-aws/pull/1448

**Pull request closed without merging**
