### PR TITLE
Add example manifests for the converted singleton list API versions

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Depends on:
- #1332 
- https://github.com/crossplane/upjet/pull/410: soft dependency, this can be merged without the dependency being merged  first)

This PR introduces the example manifests for the converted singleton list API versions. It also:
- Refactors some catch-all manifests into individual unit test manifests.
- Adds the missing example-id annotations for some manifests. However, there are still over 100 manifests with missing annotations.

An example conversion is as follows:
The old (`v1beta1`) `NodeGroup.eks` API:
```yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: sample-eks-ng
spec:
  forProvider:
    region: us-west-1
    clusterNameRef: 
      name: sample-eks-cluster
    nodeRoleArnRef:
      name: sample-node-role
    subnetIdRefs:
      - name: sample-subnet1
      - name: sample-subnet2
    scalingConfig:
      - minSize: 1
        maxSize: 1
        desiredSize: 1
```

The new `v1beta2` API for this resource:
```yaml
apiVersion: eks.aws.upbound.io/v1beta2
kind: NodeGroup
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta2/nodegroup
  name: sample-eks-ng
spec:
  forProvider:
    region: us-west-1
    clusterNameRef:
      name: sample-eks-cluster
    nodeRoleArnRef:
      name: sample-node-role
    subnetIdRefs:
      - name: sample-subnet1
      - name: sample-subnet2
    scalingConfig:
      minSize: 1
      maxSize: 1
      desiredSize: 1
```

Please note the converted singleton list `spec.forProvider.scalingConfig` as usual. The converted versions have been converted using upjet's example manifest singleton list conversion [utility](https://github.com/crossplane/upjet/blob/a444cc1abcd33a361bf406f87d4f729a26d6fdae/pkg/examples/conversion/example_conversions.go#L26). See https://github.com/crossplane/upjet/pull/397 for further details.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

- `examples/opensearchserverless/v1beta1/security_config` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9314611172
- `examples/apigateway/v1beta2/stage.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9451025216 (import step disabled)
- `examples/apigateway/v1beta2/usageplan.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9454049761 (import step disabled for Stage resources)
- `examples/apigateway/v1beta2/methodsettings.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9454319970 (import step disabled)
- `examples/autoscaling/v1beta2/attachment.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9318575157
- `examples/backup/v1beta2/plan.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9318291621
- `examples/cloudfront/v1beta2/fieldlevelencryptionprofile.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9322292877
- `examples/cloudfront/v1beta2/fieldlevelencryptionconfig.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9322409856
- `examples/connect/v1beta2/routingprofile.yaml` => Uptest fails because the quota of the instance resource-dependent to this resource has been reached.
```
    message: 'async create failed: failed to create the resource: [{0 creating Connect
      Instance: ServiceQuotaExceededException: Quota limit reached for number of instance
      for account:153891904029. Please request service limit increase before retrying.  []}]'
```
- `examples/glue/v1beta2/job.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9318566047
- `examples/ec2/v1beta2/vpcendpoint.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9314608095
- `examples/ec2/v1beta2/route.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9318561886
- `examples/eks/v1beta2/nodegroup.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9314605490
- `examples/elasticache/v1beta2/replicationgroup.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9318556431
- `examples/transfer/v1beta1/connector.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9449697628
- `examples/transfer/v1beta2/connector.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9450123203
- `examples/ec2/v1beta2/instance.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9454636081
- `examples/elasticsearch/v1beta2/domain.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9455074123
- `examples/firehose/v1beta2/deliverystream.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9454952112
- `examples/fis/v1beta2/experimenttemplate.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9455012117
- `examples/elasticbeanstalk/v1beta1/application.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9455853818
- `examples/elasticbeanstalk/v1beta2/application.yaml` => Uptest failed due to the following issue:
``` 
case.go:363: conversion webhook for elasticbeanstalk.aws.upbound.io/v1beta2, Kind=Application failed: Post "https://provider-aws-elasticbeanstalk.upbound-system.svc:9443/convert?timeout=30s": dial tcp 10.96.123.137:9443: connect: connection refused
```
Manually tested:
```
> kubectl get application.v1beta2.elasticbeanstalk.aws.upbound.io/first-app-test-qwerty-test -o yaml | yq '.status.conditions'

- lastTransitionTime: "2024-06-10T21:54:26Z"
  reason: Available
  status: "True"
  type: Ready
- lastTransitionTime: "2024-06-10T21:54:23Z"
  reason: ReconcileSuccess
  status: "True"
  type: Synced
- lastTransitionTime: "2024-06-10T21:54:25Z"
  reason: Success
  status: "True"
  type: LastAsyncOperation
- lastTransitionTime: "2024-06-10T21:55:11Z"
  reason: UpToDate
  status: "True"
  type: Test
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/opensearchserverless/v1beta1/securityconfig.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/v1beta2/nodegroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/v1beta2/nodegroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/opensearchserverless/v1beta1/securityconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/backup/v1beta2/plan.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudfront/v1beta2/fieldlevelencryptionconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticache/v1beta2/replicationgroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/v1beta2/nodepool.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/route.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/glue/v1beta2/job.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/connect/v1beta2/routingprofile.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudfront/v1beta2/fieldlevelencryptionprofile.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/autoscaling/v1beta2/attachment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/stage.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/usageplan.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/stage.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudfront/v1beta2/fieldlevelencryptionprofile.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudfront/v1beta2/fieldlevelencryptionconfig.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/opensearchserverless/v1beta1/securityconfig.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/v1beta2/nodegroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/transfer/v1beta1/connector.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/transfer/v1beta2/connector.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/stage.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/usageplan.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/methodsettings.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/methodsettings.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/usageplan.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/methodsettings.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/instance.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticbeanstalk/v1beta2/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticbeanstalk/v1beta2/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/firehose/v1beta2/deliverystream.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/fis/v1beta2/experimenttemplate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticsearch/v1beta2/domain.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticbeanstalk/v1beta1/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticbeanstalk/v1beta2/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/autoscaling/v1beta2/attachment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticache/v1beta2/replicationgroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudfront/v1beta2/fieldlevelencryptionconfig.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/backup/v1beta2/plan.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/v1beta2/nodepool.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/firehose/v1beta2/deliverystream.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/v1beta2/nodegroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudfront/v1beta2/fieldlevelencryptionprofile.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/instance.yaml"

**Review by turkenf — APPROVED** [review]
Thank you @ulucinar, LGTM.

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta2/instance.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/opensearchserverless/v1beta1/securityconfig.yaml"

**Pull request merged**
