### PR TITLE
Bump upjet to v1.4.0

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Related with: #1311 

This PR bumps the upjet dependency to `v1.4.0` and generates the secret references under `spec.initProvider` API trees for the sensitive MR parameters.

`spec.forProvider.user` of the `Broker.mq` dependency is moved to `spec.initProvider.user` in the `User.mq` example manifest to ignore the desired set of broker users declared via the `Broker.mq` MR and to prevent a race between the `Broker.mq` & `User.mq` controllers on the (external) broker users. We now also do a late-initialization configuration for `spec.forProvider.user` of `Broker.mq` so that it will be late-initialized iff the `spec.initProvider.user` is not set. This configuration is done to prevent an "unintended" race condition between the aforementioned controllers in cases where the client of the `Broker.mq` API deliberately disables broker user lifecycle management by only setting `spec.initProvider.user` and leaving `spec.forProvider.user` unset.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

- A successful uptest run for `User.v1alpha1.mq` has been registered here: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9223380910/
- A successful uptest run for `ClusterAuth.eks` has been registered here: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9223465142/
- A successful uptest run for `Budget.budgets` has been registered here: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9223714803
- A successful uptest run for `Policy.iot` has been registered here: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9223739185

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/mq/v1alpha1/user.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/v1beta1/clusterauth.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/budgets/v1beta1/budget.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/iot/v1beta1/policy.yaml"

**Review by turkenf — APPROVED** [review]
Thank you @ulucinar, LGTM.

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

**Pull request merged**
