### PR TITLE
feat(elasticache/serverless): Add endpoint and reader_endpoint connec…

### LINKED ISSUE #1568: [Bug]: writeConnectionSecretToRef on ServerlessCache Does Not Write Data to Secret
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

elasticache.aws.upbound.io/v1beta1 - ServerlessCache

### Resource MRs required to reproduce the bug

```
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ServerlessCache
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta1/serverlesscache
  labels:
    testing.upbound.io/example-name: example
  name: example-random
spec:
  forProvider:
    cacheUsageLimits:
      - dataStorage:
          - maximum: 10
            unit: GB
        ecpuPerSecond:
          - maximum: 5000
    description: Test Server
    engine: memcached
    majorEngineVersion: "1.6"
    region: us-west-1
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    writeConnectionSecretToRef:
      name: example-random
      namespace: default
```

### Steps to Reproduce

- Apply the resource using kubectl apply -f serverless-cache.yaml.
- Check the contents of the referenced secret (example-random).

### What happened?

It appears that the writeConnectionSecretToRef functionality in the ServerlessCache resource is not functioning as expected. When specifying a secret reference in writeConnectionSecretToRef, the secret is created, but it remains empty. This behavior is inconsistent with the expected functionality, where connection details (e.g., endpoint, username, password) should be written to the specified secret.

### Relevant Error Output Snippet

_No response_

### Crossplane Version

v1.17.0

### Provider Version

v1.17.0

### Kubernetes Version

v1.29.0

### Kubernetes Distribution

1.31

### Additional Info

The issue may be connected to this configuration:
[config.go#L178](https://github.com/crossplane-contrib/provider-upjet-aws/blob/cc7b958eb41f4466d707cedf8862d8369e15e43c/config/elasticache/config.go#L178).

### PR DESCRIPTION
**Pull request by portswigger-tim**
…tionDetails

### Description of your changes

Adds connection details for `ServerlessCache` instances. 

Fixes #1568

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/elasticache/v1beta1/serverlesscache.yaml"

**Comment by portswigger-tim** [comment]
Here are some references to make help make sure that I got this correct:

- **Terraform attribute reference:** https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/elasticache_serverless_cache#endpoint-block

- **Implementation inspired by the _almost_ identical memorydb config:** https://github.com/crossplane-contrib/provider-upjet-aws/blob/main/config/memorydb/config.go#L18-L33

**Review by turkenf — COMMENTED** [review]
Thank you for your effort in this PR @portswigger-tim. Could you please test the resource manually and verify that the connection keys and values ​​​​are coming to the secret correctly? It would be great if you could add the results to the PR description.

**Comment by portswigger-tim** [comment]
Close, but not quite:

```
Name:         platform-valkey-redis
Namespace:    platform
Labels:       <none>
Annotations:  <none>

Type:  connection.crossplane.io/v1alpha1

Data
====
endpoint_0_address:         64 bytes
reader_endpoint_0_address:  64 bytes

```
I'm guessing that the type is not quite right on the port.

**Comment by portswigger-tim** [comment]
@turkenf - this is ready for review 🎉

**Pull request merged**
