### PR TITLE
Bump Terraform provider version to v5.50.0

### LINKED ISSUE #1317: Unpin the `aws-sdk-go-v2` dependency
### What problem are you facing?

We've pinned the `aws-sdk-go-v2` dependency to resolve an [issue](https://github.com/crossplane-contrib/provider-upjet-aws/issues/1248) with a quick workaround. However, we will need to update this dependency at a point in time and we need to address the underlying issue by changing how we use the AWS Go SDK to fetch the EKS cluster credentials.

We need to verify the `ClusterAuth.eks` functionality before merging #1315.

This issue also demonstrates the extra maintenance burden on us when we implement resources using the AWS Go SDK.

### How could Official AWS Provider help solve your problem?

Let's find out how we should now fetch the credentials using the AWS Go SDK and remove the pin.

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Fixes #1317 
Depends on: https://github.com/upbound/terraform-provider-aws/pull/243

This PR bumps the Terraform provider version to v5.50.0 and the Go version to `1.22` as the underlying provider uses Go version. 

We need to make sure that the `ClusterAuth.eks` resource is functional as we also update the aws-sdk-v2 version to match the version consumed in the Terraform provider (relevant issue: #1248).

Thanks to @mbbush for the [PR](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1271) to upgrade Terraform provider. The commit with ID [aca95c9](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1271/commits/aca95c9b4d35e00a34adf048ddbf4eee06e575d6) was cherry-picked, we appreciate his efforts in increasing our automated testing coverage 🙌 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Fix `ClusterAuth.eks`: #1317 
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

**Breaking CRD OpenAPI v3 schema changes**

1. `package/crds/cloud9.aws.upbound.io_environmentec2s.yaml`
Uptest run: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9206624705
2. `package/crds/dms.aws.upbound.io_eventsubscriptions.yaml`
Uptest run: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9207519365
3. `package/crds/fsx.aws.upbound.io_ontapfilesystems.yaml`
Uptest run: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9206624036
4. `package/crds/memorydb.aws.upbound.io_users.yaml`
Uptest run: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9206623035

**Native schema version changes**

- `aws_secretsmanager_secret_rotation`
Uptest run: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9206625332

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/secretsmanager/v1beta1/secretrotation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/secretsmanager/v1beta1/secretrotation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloud9/v1beta1/environmentec2.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/fsx/v1beta1/ontapfilesystem.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/memorydb/v1beta1/user.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/memorydb/v1beta1/user.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/fsx/v1beta1/ontapfilesystem.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloud9/v1beta1/environmentec2.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/secretsmanager/v1beta1/secretrotation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dms/v1beta1/eventsubscription-without-source-id.yaml"

**Review by turkenf — APPROVED** [review]
Thank you @ulucinar, LGTM.

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

**Review by mergenci — APPROVED** [review]
Thanks @ulucinar 🙏 Updates to controllers puzzled me, yet they seem unharmful.

**Pull request merged**
