### PR TITLE
Bump Terraform provider version to v5.78.0

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR bumps Terraform provider version to `v5.78.0`

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

- `examples/apigateway/v1beta1/account.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12242575223
- `examples/apigateway/v1beta1/deployment.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12243219442
- `examples/apigateway/v1beta2/stage.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12243136491
- `examples/batch/v1beta1/jobdefinition.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12242913413
- `examples/cloudwatchevents/v1beta1/bus.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12243235464
- `examples/dataexchange/v1beta1/dataset.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12243242620
- `examples/ec2/v1beta2/vpcendpoint.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12255066212
- `examples/imagebuilder/v1beta1/distributionconfiguration.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12243166571
- `examples/s3/v1beta1/bucket.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12255068647
- `examples/deploy/v1beta1/deploymentgroup.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12252335011

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/batch/v1beta1/jobdefinition.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta1/vpc.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta1/vpc.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/batch/v1beta1/jobdefinition.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta1/account.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/batch/v1beta1/jobdefinition.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta2/stage.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/deploy/v1beta1/deploymentgroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/imagebuilder/v1beta1/distributionconfiguration.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/s3/v1beta1/bucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/apigateway/v1beta1/deployment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudwatchevents/v1beta1/bus.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/dataexchange/v1beta1/dataset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/deploy/v1beta1/deploymentgroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/s3/v1beta1/bucket.yaml"

**Review by mergenci — APPROVED** [review]
Thanks @turkenf 🙏 LGTM. I updated the Uptest links of VPCEndpoint and Bucket resources in the PR description, FYI.

**Pull request merged**
